### ISSUE TITLE
Кросс-проверка

### ISSUE THREAD

**Issue by aa1dar** [TheLastFlame/yss_todo#1]
Привет. Я проверял твою домашку. По критериям у тебя полный балл, т.е. 26, но у тебя есть пара неприятных багов:

1. Иконка скрытия выполненных задач дублируется:
![image](https://github.com/TheLastFlame/yss_todo/assets/53058708/29c9e4e1-ae3d-4461-9e4e-130adfde54cb)

steps to reproduce: 
1) создать достаточно задач, чтобы экран при скролле полностью сжимал appbar, в моем случае 8
2) пометить примерное половину задач как выполненные, в моем случае 5
3) проскроллить в конец страницы, нажать на иконку скрыть выполненные
4) appbar экспандится, при этом иконка глазика дублируется

2. Плывет верстка попапа создания задачи на маленьких экранах c русской локалью:
![image](https://github.com/TheLastFlame/yss_todo/assets/53058708/0cecbd94-0892-4ce0-8e6a-7caf077e4785)

Для тестирования использовался физический девайс: Samsung A52s

3. Возможность создания пустой задачи; Было бы круто если ты не будешь позволять создавать пустые задачи, это мелочь, но приятно.

**Comment by TheLastFlame** [comment]
Привет ^^
1. Про баг со сливером знаю. Проблема в том, что все изменения привязаны к прослушивателю скролл-контроллера, а он не реагирует на изменения размеров экрана. Не придумал, как это исправить пока.

2. Понял, спасибо. Надо будет во Wrap обернуть. Ну и во второй версии этот баг, скорее всего, вообще невозможно должно быть поймать, так как пропал пункт Критического приоритета, который оказался критически длинным.

3. Это ожидаемое поведение) Необходимо для быстрого тестирования и отладки -- возможности быстро добавить много элементов для тестирования сливера. Кроме того, не вижу никакого смысла в такой валидации, так как можно, например, создать пустой таск только со временем выполнения -- просто как напоминание. 

Большое спасибо за ревью))
